version: '4.36.0'

services:
  kotlin-restful-api:
    container_name: kotlin-restful-api
    image: kotlin-restful-api:0.0.1
    ports:
      - 8080:8080
    environment:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: iqbal088
      DATABASE_URL: jdbc:postgresql://kotlin-restful-api-postgres:5432/restful-api
  kotlin-restful-api-postgres:
    container_name: "kotlin-restful-api-postgres"
    image: postgres:16.1
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: iqbal088
      POSTGRES_USER: postgres
      POSTGRES_DB: restful-api


